openapi: "3.0.3"
info:
  title: ProductAPI
  description: ProductAPI
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
paths:
  /product:
    post:
      tags:
        - Product
      summary: Create product
      description: Create product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateProduct"
      responses:
        201:
          description: "success"
    get:
      tags:
        - Product
      summary: Get product
      parameters:
        - in: query
          name: page
          schema:
            type: number
            required: true
        - in: query
          name: limit
          schema:
            type: number
            required: true
      description: "Get product"
      responses:
        200:
          description: "success"
  /product/{id}:
    delete:
      tags:
        - Product
      summary: Delete product
      description: Delete product
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        200:
          description: "success"
    patch:
      tags:
        - Product
      summary: Update product name or description
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        200:
          description: "success"

components:
  schemas:
    CreateProduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    GeneralResponse:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
        data:
          type: object