openapi: "3.0.3"
info:
  title: ProductAPI
  description: ProductAPI
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
paths:
  /product:
    post:
      tags:
        - Product
      summary: Create product
      description: Create product
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/CreateProduct"
      responses:
        201:
          description: "success"
    get:
      tags:
        - Product
      summary: Get product
      description: "Get product"
      responses:
        200:
          description: "success"

components:
  schemas:
    CreateProduct:
      type: object
      properties:
        name:
          type: string
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    GeneralResponse:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
        data:
          type: object