name: Test with Docker

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dockertest
        run: go get -u github.com/golang/dockertest

      - name: Test with Docker
        run: go test -v $(go list ./... | grep -v /vendor/) -timeout 30m -count 1 -run TestWithDocker
